import "@/style/globals.css";
import Fonts from "@/components/Font";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ko">
            <Fonts />
            <body>{children}</body>
        </html>
    );
}
